version: '3.4'

services:
  csharp-httpclient-delegatinghandler:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AuthenticationConfiguration__Url=https://localhost:3001
      - AuthenticationConfiguration__ClientId=9edead392da834f54c19
      - AuthenticationConfiguration__ClientSecret=ecafa4ec-c49e-4bdc-ad39-b9e8a4789da8
      - AuthenticationConfiguration__GrantType=client_credentials
      - DataConfiguration__Url=https://localhost:3002
      - Serilog__MinimumLevel=Information
      - Serilog__WriteTo__0__Name=Console
      - TZ=Asia/Bangkok
    ports:
      - "3000:80"
